apiVersion: v1
kind: ServiceAccount
metadata:
  name: nodesynack
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nodesynack
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list", "watch", "update"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create", "patch", "update", "watch"]
# Optional but nice: new events.k8s.io API
- apiGroups: ["events.k8s.io"]
  resources: ["events"]
  verbs: ["create", "patch", "update", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: nodesynack
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: nodesynack
subjects:
- kind: ServiceAccount
  name: nodesynack
  namespace: kube-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodesynack
  namespace: kube-system
  labels:
    app: nodesynack
spec:
  selector:
    matchLabels:
      app: nodesynack
  replicas: 3
  template:
    metadata:
      labels:
        app: nodesynack
    spec:
      hostNetwork: true
      serviceAccountName: nodesynack
      containers:
      - name: nodesynack
        image: paulgmiller/nodesynack:3453695 
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 128Mi
